project:
  type: website
website:
  title: "Lipidomics analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: doc/learning.qmd
        text: "Report"
  page-footer:
    center:
      - text: "License: CC BY 4.0"
format:
  html:
    theme: materia
knitr:
  opts_chunk:
    echo: False
editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: true


