project:
  type: website
website:
  title: "Lipidomics analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: doc/learning.qmd
        text: "Report"
format:
  html:
    theme: materia
knitr:
  opts_chunk:
    echo: False
