---
title: "Draft Quarto document"
author: 
  - name: "Ulises H Guzman"
    orcid: 0000-0000-0000-0000
    email: uliseshguzman@gmail.com
    affiliations:
      - name: NNF Center for Protein research
        address: København
        city: Copenhagen 
        postal-code: 2200
format: html
execute:
  echo: true
editor:
    markdown:
        wrap: 72
        cannonical: true
---

## Header 1

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
#| include: false
# knitr::opts_chunk$set(echo = TRUE)
```

#Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} (SUM	24
value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Description statistics of the metabolites")
```

```{r}
tar_read(fig_metabolite_distribution)
```

```{r}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

```{r}
lipidomics %>% column_values_to_snake_case(metabolite)
```

```{r}
lipidomics %>% metabolites_to_wider()


lipidomics_wider <- lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  metabolites_to_wider()
```

```{r}
recipe(class ~ metabolite_lipid_ch_3_1 + age + gender,
  data = lipidomics_wider
)
```

```{r}
recipe(lipidomics_wider) %>%
  update_role(metabolite_lipid_ch_3_1, age, gender,
    new_role = "predictor"
  ) %>%
  update_role(class, new_role = "outcome") %>%
  step_normalize(starts_with("metabolite_"))
```

```{r}
recipe_specs <- lipidomics_wider %>%
  create_recipe_spec(metabolite_lipid_ch_3_1)
recipe_specs
```

```{r}
workflow() %>%
  add_model(log_reg_specs) %>%
  add_recipe(recipe_specs)
```

```{r}
model_workflow <- create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wider %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
)

model_workflow
```

```{r}
fitted_model <- model_workflow %>%
  fit(lipidomics_wider)

fitted_model
```

```{r}
fitted_model %>%
  extract_fit_parsnip() %>%
  broom::tidy(exponentiate = TRUE)
```

```{r}
fitted_model %>% tidy_model_output()
```

```{r}
create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wider %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
) %>%
  fit(lipidomics_wider) %>%
  tidy_model_output()
```

##Running multiple models

```{r}
split_by_metabolite(lipidomics)
```

```{r}


model_estimates <- lipidomics %>%
  split_by_metabolite() %>%
  map(generate_model_results) %>%
  list_rbind() %>% 
  filter(str_detect(term, "metabolite_"))

model_estimates

```

```{r}
model_estimates= lipidomics %>%
  mutate(term = metabolite) %>%
  column_values_to_snake_case(term) %>%
  mutate(term = str_c("metabolite_", term)) %>%
  distinct(term, metabolite) %>%
  right_join(model_estimates, by = "term")
model_estimates


```

### Figure of model estimates

```{r}
model_estimates <- tar_read(df_model_estimates)
model_estimates
```

```{r}
plot_estimates(model_estimates)
```

```{r}

tar_read(fig_model_estimates)
```
